#!/usr/bin/env python3
"""
Telemetry Writer — Phase 5.7

Writes telemetry events for each pipeline stage.
Each event is a real record, generated by actual function calls,
NOT simulated or hand-written.

Events:
  - task event (task received)
  - route event (Router decision)
  - memory event (Memory retrieval)
  - skill event (Skill loaded)
  - execution event (Runtime execution)
  - validation event (Validation result)
  - outcome event (Final outcome)
  - failure event (On failure)
"""

import os
import yaml
from datetime import datetime, timezone

BASE = "/home/shade/.agents"
TELEMETRY_DIR = os.path.join(BASE, "runtime", "telemetry")

# Phase 5.9: Import atomic write utility
import sys
sys.path.insert(0, os.path.join(BASE, "runtime", "loop-controller"))
from file_utils import atomic_yaml_write


def _ensure_dir():
    os.makedirs(TELEMETRY_DIR, exist_ok=True)


def _write_event(event_type: str, event: dict):
    """Write an event to the appropriate telemetry file."""
    _ensure_dir()

    file_map = {
        "task": "task-events.md",
        "route": "routing-events.md",
        "memory": "memory-events.md",
        "skill": "skill-events.md",
        "execution": "runtime-events.yaml",
        "validation": "runtime-events.yaml",
        "outcome": "runtime-events.yaml",
        "failure": "failure-events.yaml",
    }

    filename = file_map.get(event_type, "runtime-events.yaml")
    filepath = os.path.join(TELEMETRY_DIR, filename)

    if filename.endswith(".yaml"):
        # YAML format: append event to list
        existing = []
        if os.path.exists(filepath):
            with open(filepath) as f:
                content = f.read()
                if content.strip():
                    try:
                        parsed = yaml.safe_load(content)
                        if isinstance(parsed, list):
                            existing = parsed
                    except Exception:
                        pass

        existing.append(event)

        # Phase 5.9: Atomic write to prevent corruption
        header = f"# {event_type.title()} Events — Auto-generated by Agent OS Pipeline\n# Last updated: {datetime.now(timezone.utc).isoformat()}"
        atomic_yaml_write(filepath, existing, header_lines=[header])
    else:
        # Markdown format: append event
        timestamp = event.get("timestamp", datetime.now(timezone.utc).isoformat())
        with open(filepath, "a") as f:
            f.write(f"\n## {event_type.title()} Event — {timestamp}\n\n")
            f.write("```yaml\n")
            yaml.dump(event, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
            f.write("```\n")


def emit_task_event(execution_id: str, task_id: str, task_text: str, provider: str, model: str, runtime_mode: str):
    """Emit a task event when a task is received."""
    event = {
        "event_type": "task",
        "execution_id": execution_id,
        "task_id": task_id,
        "task_text": task_text[:200],
        "provider": provider,
        "model": model,
        "runtime_mode": runtime_mode,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("task", event)
    return event


def emit_route_event(execution_id: str, task_id: str, route_decision: dict):
    """Emit a route event when the Router makes a decision."""
    event = {
        "event_type": "route",
        "execution_id": execution_id,
        "task_id": task_id,
        "intent": route_decision.get("intent", ""),
        "domains": route_decision.get("domains", []),
        "lead_skill": route_decision.get("lead_skill", ""),
        "support_skills": route_decision.get("support_skills", []),
        "confidence": route_decision.get("confidence", ""),
        "memory_influence": route_decision.get("memory_influence", ""),
        "rules_applied": route_decision.get("rules_applied", []),
        "started_at": route_decision.get("started_at", ""),
        "completed_at": route_decision.get("completed_at", ""),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("route", event)
    return event


def emit_memory_event(execution_id: str, task_id: str, memory_context: dict):
    """Emit a memory event when memories are retrieved."""
    event = {
        "event_type": "memory",
        "execution_id": execution_id,
        "task_id": task_id,
        "mode": memory_context.get("memory_mode", "off"),
        "retrieved": memory_context.get("total_retrieved", 0),
        "memory_ids": memory_context.get("ranking", []),
        "hypothesis_count": len(memory_context.get("hypotheses", [])),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("memory", event)
    return event


def emit_skill_event(execution_id: str, task_id: str, skill_context: dict):
    """Emit a skill event when skills are loaded."""
    event = {
        "event_type": "skill",
        "execution_id": execution_id,
        "task_id": task_id,
        "lead_skill": skill_context.get("lead_skill", {}).get("name", ""),
        "support_skills": [s.get("name", "") for s in skill_context.get("support_skills", [])],
        "skills_loaded": skill_context.get("skills_loaded", []),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("skill", event)
    return event


def emit_execution_event(execution_id: str, task_id: str, exec_result: dict):
    """Emit an execution event when runtime execution completes."""
    event = {
        "event_type": "execution",
        "execution_id": execution_id,
        "task_id": task_id,
        "status": exec_result.get("status", ""),
        "latency_ms": exec_result.get("latency_ms", 0),
        "tokens": exec_result.get("token_usage", {}),
        "session_id": exec_result.get("session_id", ""),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("execution", event)
    return event


def emit_validation_event(execution_id: str, task_id: str, validation_result: dict):
    """Emit a validation event."""
    event = {
        "event_type": "validation",
        "execution_id": execution_id,
        "task_id": task_id,
        "status": validation_result.get("validation_status", ""),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("validation", event)
    return event


def emit_outcome_event(execution_id: str, task_id: str, outcome: str, summary: dict):
    """Emit an outcome event when the pipeline completes."""
    event = {
        "event_type": "outcome",
        "execution_id": execution_id,
        "task_id": task_id,
        "outcome": outcome,
        "summary": summary,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("outcome", event)
    return event


def emit_failure_event(execution_id: str, task_id: str, stage: str, error: str):
    """Emit a failure event."""
    event = {
        "event_type": "failure",
        "execution_id": execution_id,
        "task_id": task_id,
        "stage": stage,
        "error": str(error),
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    _write_event("failure", event)
    return event