#!/usr/bin/env python3
"""
Phase 8.3 — Release Hardening Tests

Validates:
  A. Artifact Authority — loop_id consistency across all runtime artifacts
  B. Cross-loop Memory Lineage — Run 1 hypothesis retrievable in Run 2
  C. Hypothesis Retrieval Lane — two-pass retrieval with separate lanes
  D. Validation Aggregation — cross-run observation accumulation
  E. Promotion Provenance — validated_ids → promoted_ids traceable chain
"""

import sys
import os
import unittest
import tempfile
import yaml
import copy
from datetime import datetime, timezone

# ── Path setup ────────────────────────────────────────────────────
_AGENT_HOME = os.environ.get("AGENT_OS_HOME", "/home/shade/.agents")
_COLLECTOR_DIR = os.path.join(_AGENT_HOME, "runtime", "memory-feedback", "collector")
_PROMOTION_DIR = os.path.join(_AGENT_HOME, "runtime", "memory-feedback", "promotion")
_RETRIEVAL_DIR = os.path.join(_AGENT_HOME, "runtime", "memory-feedback", "retrieval")
_LOOP_DIR = os.path.join(_AGENT_HOME, "runtime", "loop-controller")

for d in [_COLLECTOR_DIR, _PROMOTION_DIR, _RETRIEVAL_DIR, _LOOP_DIR]:
    if d not in sys.path:
        sys.path.insert(0, d)

from retrieval_optimizer import retrieve, save_retrieval_history, load_yaml, \
    RETRIEVAL_INDEX, RETRIEVAL_HISTORY
from collector import collect_from_trace_ids, write_candidates_output, \
    load_collector_state, CANDIDATES_FILE, COLLECTOR_STATE_FILE
from validator import validate_candidates, group_candidates_by_memory, \
    validate_memory_group, OBSERVATION_LOG_FILE, enrich_groups_with_observation_log
from promoter import promote_validated, load_memory_index, \
    VALIDATION_FILE, OUTPUT_FILE as PROMOTER_OUTPUT_FILE


# ── Helpers ───────────────────────────────────────────────────────

def _make_trace_fixture(execution_id, task_id="RT-TEST", status="success",
                         session_id="sess-test", response="Test response with analysis"):
    return {
        "execution_id": execution_id,
        "task_id": task_id,
        "status": status,
        "memory_mode": "enabled",
        "agent_invocation": {
            "session_id": session_id,
            "tokens": {"total": 500},
            "latency_ms": 1200,
        },
        "agent_response": response,
        "memory_retrieval": {
            "memories_used": [],
            "memory_influence": "hypothesis_confirmed",
        },
        "orchestrator": {"anti_pattern_alert": False},
        "model": "test-model",
    }


def _make_candidate_fixture(memory_id, execution_id, quality_score=4.0,
                             candidate_type="reinforce", loop_id=None):
    return {
        "candidate_id": f"CAND-{execution_id}-{memory_id}",
        "source_execution": execution_id,
        "target_memory": memory_id,
        "candidate_type": candidate_type,
        "quality_score": quality_score,
        "quality_breakdown": {
            "completeness": 4, "accuracy": 4, "structure": 4,
            "actionability": 4, "novelty": 4,
        },
        "reasoning": f"Test candidate for {memory_id}",
        "evidence": {
            "session_id": "sess-test",
            "output_hash": "abc123def456",
            "is_real_execution": True,
        },
        "outcome": "promoted",
        "loop_id": loop_id or "LOOP-PHASE83-TEST",
    }


# =============================================================================
# A. Artifact Authority — loop_id consistency
# =============================================================================

class TestArtifactAuthority(unittest.TestCase):
    """All runtime artifacts from the same run must share the same loop_id."""

    def setUp(self):
        self.loop_id = "LOOP-ARTIFACT-001"
        self.tmpdir = tempfile.mkdtemp()

    def test_candidate_loop_id_set(self):
        """Candidates generated by collector must carry loop_id."""
        candidates = []
        for i in range(3):
            c = _make_candidate_fixture(f"H-TEST-{i}", f"EXEC-{i}", loop_id=self.loop_id)
            candidates.append(c)

        for c in candidates:
            self.assertEqual(c["loop_id"], self.loop_id,
                             f"Candidate {c['candidate_id']} missing correct loop_id")

    def test_candidate_loop_id_consistency(self):
        """All candidates from same run must have the same loop_id."""
        candidates = [
            _make_candidate_fixture("H-A", "EXEC-1", loop_id=self.loop_id),
            _make_candidate_fixture("H-B", "EXEC-2", loop_id=self.loop_id),
            _make_candidate_fixture("H-C", "EXEC-3", loop_id=self.loop_id),
        ]

        unique_loop_ids = set(c["loop_id"] for c in candidates)
        self.assertEqual(len(unique_loop_ids), 1,
                         f"Expected 1 loop_id, got {len(unique_loop_ids)}: {unique_loop_ids}")
        self.assertEqual(unique_loop_ids.pop(), self.loop_id)

    def test_validator_passes_loop_id(self):
        """Validator must stamp loop_id on each result."""
        candidates = [
            _make_candidate_fixture("H-001-TEST", "EXEC-A", loop_id=self.loop_id),
            _make_candidate_fixture("H-001-TEST", "EXEC-B", loop_id=self.loop_id),
        ]
        results = validate_candidates(candidates, quiet=True, loop_id=self.loop_id)

        for r in results:
            self.assertEqual(r.get("loop_id"), self.loop_id,
                             f"Validation result for {r['memory_id']} missing loop_id")

    def test_promoter_provenance_has_loop_id(self):
        """Promotion result must include provenance with loop_id."""
        validated_result = {
            "memory_id": "H-001-TEST",
            "best_candidate_id": "CAND-EXEC-A-H-001-TEST",
            "status": "validated",
            "validation_runs": 2,
            "quality_score": 4.5,
            "confidence": 0.4,
            "evidence_sources": ["EXEC-A", "EXEC-B"],
            "gate_results": {"M1_provenance": "pass"},
        }

        result = promote_validated(validated_result, loop_id=self.loop_id)

        if result["status"] == "applied":
            self.assertIn("provenance", result, "Applied result must have provenance")
            self.assertEqual(result["provenance"]["loop_id"], self.loop_id)
            self.assertIn("observation_sources", result["provenance"])
            self.assertIn("observation_count", result["provenance"])

    def test_retrieval_history_has_loop_id(self):
        """Retrieval history entries must record loop_id."""
        query = {"task_text": "test task", "category": "backend"}
        result = {"results": []}

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            tmp_path = f.name
            yaml.dump({"version": "1.0", "phase": "5.8", "retrievals": []}, f)

        try:
            import retrieval_optimizer as ro
            original = ro.RETRIEVAL_HISTORY
            ro.RETRIEVAL_HISTORY = tmp_path

            save_retrieval_history(query, result, loop_id=self.loop_id)

            with open(tmp_path) as f:
                saved = yaml.safe_load(f)

            self.assertGreater(len(saved.get("retrievals", [])), 0)
            self.assertEqual(saved["retrievals"][-1]["loop_id"], self.loop_id)

            ro.RETRIEVAL_HISTORY = original
        finally:
            os.unlink(tmp_path)

    def test_write_candidates_output_has_loop_id(self):
        """write_candidates_output must include loop_id in YAML output."""
        candidates = [_make_candidate_fixture("H-TEST", "EXEC-1", loop_id=self.loop_id)]

        with tempfile.NamedTemporaryFile(mode="r", suffix=".yaml", delete=False) as f:
            tmp_path = f.name

        try:
            import collector as col
            original = col.CANDIDATES_FILE
            col.CANDIDATES_FILE = tmp_path

            write_candidates_output(candidates, ["EXEC-1"], loop_id=self.loop_id)

            with open(tmp_path) as f:
                saved = yaml.safe_load(f)

            self.assertEqual(saved.get("loop_id"), self.loop_id)
            self.assertEqual(saved["candidates"][0]["loop_id"], self.loop_id)

            col.CANDIDATES_FILE = original
        finally:
            os.unlink(tmp_path)


# =============================================================================
# B. Cross-loop Memory Lineage — Run 1 → Run 2 retrieval
# =============================================================================

class TestCrossLoopMemoryLineage(unittest.TestCase):
    """Hypothesis created in Run 1 must be retrievable in Run 2."""

    def setUp(self):
        self.loop_id_r1 = "LOOP-RUN1-001"
        self.loop_id_r2 = "LOOP-RUN2-001"

    def test_hypothesis_survives_across_runs(self):
        """Run 1 hypothesis is present in retrieval index and can be retrieved by Run 2."""
        index = load_memory_index()
        memories = index.get("memories", [])

        hypothesis_ids = [m["memory_id"] for m in memories if m.get("type") == "hypothesis"]
        self.assertGreater(len(hypothesis_ids), 0,
                           "No hypotheses exist in retrieval index — cannot test cross-run lineage")

        # Pick a hypothesis with strong keyword overlap for a realistic query
        # Use a hypothesis with tags that match a common backend/state query
        test_hyp_id = hypothesis_ids[0]
        h_mem = next(m for m in memories if m["memory_id"] == test_hyp_id)

        # Simulate Run 2: query related to the hypothesis domain
        query = {
            "task_text": "Debug session state inconsistency in Java service",
            "category": h_mem.get("category", "backend"),
            "domains": h_mem.get("tags", []),
            "roles": h_mem.get("roles", []),
            "keywords": h_mem.get("tags", []),
            "difficulty": "medium",
            "exclude_hypothesis": False,
        }

        result = retrieve(query)

        hypothesis_retrieved = [r for r in result.get("results", []) if r.get("is_hypothesis")]
        self.assertGreater(len(hypothesis_retrieved), 0,
                           f"Run 2 must retrieve at least 1 hypothesis. "
                           f"Query: {query['task_text'][:60]} — "
                           f"Total results: {len(result.get('results', []))}")

    def test_hypothesis_retrieved_for_similar_task(self):
        """Relevant hypothesis should appear when querying a similar task."""
        index = load_memory_index()
        memories = index.get("memories", [])

        # Find a hypothesis with a specific category
        backend_hypotheses = [m for m in memories
                               if m.get("type") == "hypothesis"
                               and m.get("category") == "backend"]
        if not backend_hypotheses:
            backend_hypotheses = [m for m in memories if m.get("type") == "hypothesis"]

        self.assertGreater(len(backend_hypotheses), 0, "No hypotheses to test similarity retrieval")

        h = backend_hypotheses[0]
        tags = h.get("tags", ["backend"])

        query = {
            "task_text": f"Fix issues in the same area: {tags[0] if tags else 'backend'}",
            "category": h.get("category", "backend"),
            "domains": tags,
            "roles": h.get("roles", []),
            "keywords": tags,
            "difficulty": "medium",
            "exclude_hypothesis": False,
        }

        result = retrieve(query)
        hypothesis_results = [r for r in result.get("results", []) if r.get("is_hypothesis")]

        self.assertGreater(len(hypothesis_results), 0,
                           f"Similarity query returned zero hypotheses. "
                           f"tags: {tags}, category: {h.get('category')}")

    def test_retrieval_returns_established_and_hypothesis_separately(self):
        """Retrieval must return both established and hypothesis results."""
        query = {
            "task_text": "Design a backend system with persistence",
            "category": "backend",
            "domains": ["backend", "database"],
            "roles": ["backend-architect"],
            "keywords": ["backend", "database"],
            "difficulty": "medium",
            "exclude_hypothesis": False,
        }

        result = retrieve(query)
        results = result.get("results", [])

        established = [r for r in results if not r.get("is_hypothesis")]
        hypothesis = [r for r in results if r.get("is_hypothesis")]

        # At minimum, we should have some results with established memories
        self.assertGreaterEqual(len(results), 0,
                                "Retrieval should return results (may be empty if no match)")


# =============================================================================
# C. Hypothesis Retrieval Lane — two-pass retrieval
# =============================================================================

class TestHypothesisRetrievalLane(unittest.TestCase):
    """Hypotheses must be retrievable without being promoted to established memory."""

    def test_hypothesis_has_separate_lane(self):
        """Hypothesis results must be distinguishable from established results."""
        query = {
            "task_text": "Analyze backend service performance",
            "category": "backend",
            "domains": ["backend"],
            "roles": ["backend-architect"],
            "keywords": ["backend", "performance"],
            "difficulty": "medium",
            "exclude_hypothesis": False,
        }

        result = retrieve(query)
        results = result.get("results", [])

        for r in results:
            if r.get("is_hypothesis"):
                # Hypotheses must be labeled as such
                self.assertTrue(r.get("is_hypothesis"), f"Memory {r['memory_id']} should be labeled as hypothesis")
                # Hypotheses must have a warning about unvalidated status
                if r.get("warning"):
                    self.assertIn("Unvalidated", r["warning"])

    def test_hypothesis_not_auto_promoted_to_established(self):
        """Retrieval lane must not change hypothesis type to established."""
        index = load_memory_index()
        memories = index.get("memories", [])

        hypothesis_ids = [m["memory_id"] for m in memories if m.get("type") == "hypothesis"]
        if not hypothesis_ids:
            self.skipTest("No hypotheses to test")

        test_id = hypothesis_ids[0]
        h_mem = next(m for m in memories if m["memory_id"] == test_id)

        query = {
            "task_text": "Test retrieval for hypothesis",
            "category": h_mem.get("category", "backend"),
            "domains": h_mem.get("tags", []),
            "roles": h_mem.get("roles", []),
            "keywords": h_mem.get("tags", []),
            "difficulty": "medium",
            "exclude_hypothesis": False,
        }

        result = retrieve(query)
        for r in result.get("results", []):
            if r["memory_id"] == test_id:
                self.assertEqual(r.get("type"), "hypothesis",
                                 f"Hypothesis {test_id} must remain type='hypothesis', got {r.get('type')}")
                self.assertTrue(r.get("is_hypothesis"),
                                f"is_hypothesis flag must be True for {test_id}")

    def test_ranking_test_hypothesis_visible(self):
        """At least one hypothesis must appear in retrieval results when relevant."""
        query = {
            "task_text": "Build a backend service with state management",
            "category": "backend",
            "domains": ["backend", "state"],
            "roles": ["backend-architect", "backend-engineer"],
            "keywords": ["backend", "state", "session"],
            "difficulty": "medium",
            "exclude_hypothesis": False,
        }

        result = retrieve(query)
        results = result.get("results", [])
        hypothesis_results = [r for r in results if r.get("is_hypothesis")]

        # Not all queries will match hypotheses, but we verify the structure
        for h in hypothesis_results:
            self.assertIsNotNone(h.get("static_relevance"),
                                 f"Hypothesis {h['memory_id']} missing static_relevance")
            self.assertIsNotNone(h.get("final_score"),
                                 f"Hypothesis {h['memory_id']} missing final_score")


# =============================================================================
# D. Validation Aggregation — cross-run observation
# =============================================================================

class TestValidationAggregation(unittest.TestCase):
    """Cross-loop observation accumulation must drive validation."""

    def setUp(self):
        self.loop_id_r1 = "LOOP-VALIDATE-R1"
        self.loop_id_r2 = "LOOP-VALIDATE-R2"

    def test_group_candidates_aggregates_executions(self):
        """Multiple candidates for same memory must aggregate executions."""
        candidates = [
            _make_candidate_fixture("H-AGG-001", "EXEC-R1", loop_id=self.loop_id_r1),
            _make_candidate_fixture("H-AGG-001", "EXEC-R2", loop_id=self.loop_id_r2),
        ]

        groups = group_candidates_by_memory(candidates)
        self.assertIn("H-AGG-001", groups)

        group = groups["H-AGG-001"]
        self.assertEqual(len(group["executions"]), 2,
                         f"Expected 2 executions, got {len(group['executions'])}")
        self.assertIn("EXEC-R1", group["executions"])
        self.assertIn("EXEC-R2", group["executions"])

    def test_single_observation_enters_as_hypothesis(self):
        """H-xxx with 1 observation enters as hypothesis, not validated."""
        candidates = [
            _make_candidate_fixture("H-SINGLE-001", "EXEC-S1", loop_id=self.loop_id_r1),
        ]

        groups = group_candidates_by_memory(candidates)
        status, result = validate_memory_group("H-SINGLE-001", groups["H-SINGLE-001"])

        self.assertEqual(status, "hypothesis",
                         f"Single observation H-xxx should be 'hypothesis', got '{status}'")
        self.assertEqual(result["validation_runs"], 1)

    def test_two_observations_graduates_to_validated(self):
        """H-xxx with 2 observations must graduate to validated."""
        candidates = [
            _make_candidate_fixture("H-GRAD-001", "EXEC-G1", loop_id=self.loop_id_r1),
            _make_candidate_fixture("H-GRAD-001", "EXEC-G2", loop_id=self.loop_id_r2),
        ]

        groups = group_candidates_by_memory(candidates)
        status, result = validate_memory_group("H-GRAD-001", groups["H-GRAD-001"])

        self.assertEqual(status, "validated",
                         f"Two-observation H-xxx should be 'validated', got '{status}'")
        self.assertEqual(result["validation_runs"], 2)

    def test_observation_log_enriches_groups(self):
        """Observation log entries must enrich cross-loop groups."""
        # Write a test observation log
        test_log = {
            "version": "1.0",
            "observations": [
                {
                    "memory_id": "H-ENRICH-001",
                    "source_loop": "LOOP-PREVIOUS-001",
                    "source_execution": "EXEC-PREV",
                    "session_id": "sess-prev",
                    "output_hash": "hash123",
                    "quality_score": 4.0,
                    "candidate_type": "reinforce",
                    "observed_at": datetime.now(timezone.utc).isoformat(),
                    "origin": "runtime",
                },
            ],
        }

        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            obs_path = f.name
            yaml.dump(test_log, f)

        try:
            import validator
            original = validator.OBSERVATION_LOG_FILE
            validator.OBSERVATION_LOG_FILE = obs_path

            # Create a group with 1 current candidate + 1 observation log entry
            candidates = [
                _make_candidate_fixture("H-ENRICH-001", "EXEC-NOW", loop_id=self.loop_id_r1),
            ]
            groups = group_candidates_by_memory(candidates)
            enriched = enrich_groups_with_observation_log(groups)

            self.assertIn("H-ENRICH-001", enriched)
            group = enriched["H-ENRICH-001"]

            # Should have 2 executions (1 from candidate + 1 from observation log)
            self.assertEqual(len(group["executions"]), 2,
                             f"Expected 2 executions after enrichment, got {len(group['executions'])}")

            validator.OBSERVATION_LOG_FILE = original
        finally:
            os.unlink(obs_path)


# =============================================================================
# E. Promotion Provenance — validated_ids → promoted_ids
# =============================================================================

class TestPromotionProvenance(unittest.TestCase):
    """Promotion must be driven by runtime evidence with complete provenance chain."""

    def setUp(self):
        self.loop_id = "LOOP-PROMOTE-001"

    def test_promotion_result_has_provenance(self):
        """Valid promotion result must include provenance field."""
        validated_result = {
            "memory_id": "H-PROV-001",
            "best_candidate_id": "CAND-EXEC-PROV-H-PROV-001",
            "status": "validated",
            "validation_runs": 2,
            "quality_score": 4.5,
            "confidence": 0.4,
            "evidence_sources": ["EXEC-P1", "EXEC-P2"],
            "gate_results": {"M1_provenance": "pass"},
        }

        result = promote_validated(validated_result, loop_id=self.loop_id)

        if result["status"] == "applied":
            prov = result.get("provenance", {})
            self.assertEqual(prov.get("loop_id"), self.loop_id,
                             "Provenance must track the loop that triggered promotion")
            self.assertIn("source_validation_ids", prov,
                          "Provenance must list source validation IDs")
            self.assertIn("observation_sources", prov,
                          "Provenance must list observation sources")
            self.assertIn("observation_count", prov,
                          "Provenance must track observation count")

    def test_provenance_chain_traceable(self):
        """Provenance must connect validated_ids back to evidence sources."""
        validated_result = {
            "memory_id": "H-CHAIN-001",
            "best_candidate_id": "CAND-EXEC-CHAIN-H-CHAIN-001",
            "status": "validated",
            "validation_runs": 3,
            "quality_score": 4.8,
            "confidence": 0.6,
            "evidence_sources": ["EXEC-C1", "EXEC-C2", "EXEC-C3"],
            "gate_results": {"M1_provenance": "pass"},
        }

        result = promote_validated(validated_result, loop_id=self.loop_id)

        if result["status"] == "applied":
            prov = result["provenance"]
            self.assertEqual(prov["observation_count"], 3,
                             f"Expected 3 observations, got {prov['observation_count']}")
            self.assertEqual(len(prov["observation_sources"]), 3)
            self.assertIn("EXEC-C1", prov["observation_sources"])
            self.assertIn("EXEC-C2", prov["observation_sources"])
            self.assertIn("EXEC-C3", prov["observation_sources"])

    def test_evidence_updates_track_delta(self):
        """Promotion result must track old→new evidence evolution."""
        validated_result = {
            "memory_id": "H-DELTA-001",
            "best_candidate_id": "CAND-EXEC-DELTA-H-DELTA-001",
            "status": "validated",
            "validation_runs": 2,
            "quality_score": 4.2,
            "confidence": 0.4,
            "evidence_sources": ["EXEC-D1", "EXEC-D2"],
            "gate_results": {"M1_provenance": "pass"},
        }

        result = promote_validated(validated_result, loop_id=self.loop_id)

        if result["status"] == "applied":
            self.assertIn("evidence_updates", result,
                          "Applied result must have evidence_updates")
            updates = result["evidence_updates"]
            self.assertIn("old_observation_count", updates)
            self.assertIn("new_observation_count", updates)
            self.assertIn("old_evidence_level", updates)
            self.assertIn("new_evidence_level", updates)

    def test_promotion_idempotency(self):
        """Re-promoting same memory should be skipped, not duplicated."""
        validated_result = {
            "memory_id": "H-IDEM-001",
            "best_candidate_id": "CAND-EXEC-IDEM-H-IDEM-001",
            "status": "validated",
            "validation_runs": 2,
            "quality_score": 4.0,
            "confidence": 0.4,
            "evidence_sources": ["EXEC-I1", "EXEC-I2"],
            "gate_results": {"M1_provenance": "pass"},
        }

        result = promote_validated(validated_result, loop_id=self.loop_id)

        # If skipped (because already promoted), that's acceptable
        if result["status"] == "skipped":
            self.assertIn("rejection_reason", result)
            self.assertIn("idempotency", result["rejection_reason"].lower())
        elif result["status"] == "applied":
            self.assertIn("provenance", result)


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    unittest.main(verbosity=2)